//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamirhaneApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu
    {
        public int id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int musteriId { get; set; }
        public string kayit { get; set; }
        public string randevuya_geldimi { get; set; }
    }
}
