//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamirhaneApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TamiraneDBEntities : DbContext
    {
        public TamiraneDBEntities()
            : base("name=TamiraneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<girisekrani> girisekrani { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<araclar> araclar { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
    }
}
